// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type ServerSentEventsResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { EvalsEvalItemsData, EvalsEvalItemsErrors, EvalsEvalItemsResponses, EvalsEvalSummaryData, EvalsEvalSummaryErrors, EvalsEvalSummaryResponses, GoldenGoldenSourcesData, GoldenGoldenSourcesErrors, GoldenGoldenSourcesResponses, HealthHealthData, HealthHealthResponses, HealthReadyData, HealthReadyErrors, HealthReadyResponses, ImagesGetImageData, ImagesGetImageErrors, ImagesGetImageResponses, LlmCompleteData, LlmCompleteErrors, LlmCompleteResponses, LlmStreamData, LlmStreamErrors, LlmStreamResponse, LlmStreamResponses, MetaRunEventsData, MetaRunEventsResponses, MetaStreamEventsData, MetaStreamEventsResponses, OpsSummaryData, OpsSummaryErrors, OpsSummaryResponses, ProductsCreateProductData, ProductsCreateProductErrors, ProductsCreateProductResponses, ProductsGetProductData, ProductsGetProductErrors, ProductsGetProductResponses, ProductsListProductsData, ProductsListProductsErrors, ProductsListProductsResponses, RunsCancelRunData, RunsCancelRunErrors, RunsCancelRunResponses, RunsCreateRunRouteData, RunsCreateRunRouteErrors, RunsCreateRunRouteResponses, RunsDecideRunData, RunsDecideRunErrors, RunsDecideRunResponses, RunsGetRunData, RunsGetRunErrors, RunsGetRunResponses, RunsListRunsData, RunsListRunsErrors, RunsListRunsResponses, RunsRunEventsData, RunsRunEventsErrors, RunsRunEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const healthHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthData, ThrowOnError>): RequestResult<HealthHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Ready
 */
export const healthReady = <ThrowOnError extends boolean = false>(options?: Options<HealthReadyData, ThrowOnError>): RequestResult<HealthReadyResponses, HealthReadyErrors, ThrowOnError> => (options?.client ?? client).get<HealthReadyResponses, HealthReadyErrors, ThrowOnError>({ url: '/ready', ...options });

/**
 * Eval Items
 *
 * Labelled items of the latest report with their verdicts (planted-failure gallery and the
 * TP/FP/FN/TN drill-down; `outcome` needs the positive class FAIL).
 */
export const evalsEvalItems = <ThrowOnError extends boolean = false>(options?: Options<EvalsEvalItemsData, ThrowOnError>): RequestResult<EvalsEvalItemsResponses, EvalsEvalItemsErrors, ThrowOnError> => (options?.client ?? client).get<EvalsEvalItemsResponses, EvalsEvalItemsErrors, ThrowOnError>({ url: '/v1/evals/items', ...options });

/**
 * Eval Summary
 *
 * The latest evaluator report: per-dimension precision/recall/F1, human agreement, pipeline
 * pass rates, text exactness, $/ad, latency and every PRD criterion with its target.
 */
export const evalsEvalSummary = <ThrowOnError extends boolean = false>(options?: Options<EvalsEvalSummaryData, ThrowOnError>): RequestResult<EvalsEvalSummaryResponses, EvalsEvalSummaryErrors, ThrowOnError> => (options?.client ?? client).get<EvalsEvalSummaryResponses, EvalsEvalSummaryErrors, ThrowOnError>({ url: '/v1/evals/summary', ...options });

/**
 * Golden Sources
 *
 * Where every golden reference photo comes from, its author and licence (SOURCES.md), plus
 * the product table parsed into rows.
 */
export const goldenGoldenSources = <ThrowOnError extends boolean = false>(options?: Options<GoldenGoldenSourcesData, ThrowOnError>): RequestResult<GoldenGoldenSourcesResponses, GoldenGoldenSourcesErrors, ThrowOnError> => (options?.client ?? client).get<GoldenGoldenSourcesResponses, GoldenGoldenSourcesErrors, ThrowOnError>({ url: '/v1/golden/sources', ...options });

/**
 * Get Image
 */
export const imagesGetImage = <ThrowOnError extends boolean = false>(options: Options<ImagesGetImageData, ThrowOnError>): RequestResult<ImagesGetImageResponses, ImagesGetImageErrors, ThrowOnError> => (options.client ?? client).get<ImagesGetImageResponses, ImagesGetImageErrors, ThrowOnError>({ url: '/v1/images/{image_id}', ...options });

/**
 * Complete
 */
export const llmComplete = <ThrowOnError extends boolean = false>(options: Options<LlmCompleteData, ThrowOnError>): RequestResult<LlmCompleteResponses, LlmCompleteErrors, ThrowOnError> => (options.client ?? client).post<LlmCompleteResponses, LlmCompleteErrors, ThrowOnError>({
    url: '/v1/llm/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream
 */
export const llmStream = <ThrowOnError extends boolean = false>(options: Options<LlmStreamData, ThrowOnError, LlmStreamResponse>): Promise<ServerSentEventsResult<LlmStreamResponses>> => (options.client ?? client).sse.post<LlmStreamResponses, LlmStreamErrors, ThrowOnError>({
    url: '/v1/llm/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run Events
 *
 * Schema carrier for the `GET /v1/runs/{id}/events` payloads (always empty).
 */
export const metaRunEvents = <ThrowOnError extends boolean = false>(options?: Options<MetaRunEventsData, ThrowOnError>): RequestResult<MetaRunEventsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MetaRunEventsResponses, unknown, ThrowOnError>({ url: '/v1/meta/run-events', ...options });

/**
 * Stream Events
 */
export const metaStreamEvents = <ThrowOnError extends boolean = false>(options?: Options<MetaStreamEventsData, ThrowOnError>): RequestResult<MetaStreamEventsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MetaStreamEventsResponses, unknown, ThrowOnError>({ url: '/v1/meta/stream-events', ...options });

/**
 * Summary
 */
export const opsSummary = <ThrowOnError extends boolean = false>(options?: Options<OpsSummaryData, ThrowOnError>): RequestResult<OpsSummaryResponses, OpsSummaryErrors, ThrowOnError> => (options?.client ?? client).get<OpsSummaryResponses, OpsSummaryErrors, ThrowOnError>({ url: '/v1/ops/summary', ...options });

/**
 * List Products
 */
export const productsListProducts = <ThrowOnError extends boolean = false>(options?: Options<ProductsListProductsData, ThrowOnError>): RequestResult<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError> => (options?.client ?? client).get<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError>({ url: '/v1/products', ...options });

/**
 * Create Product
 *
 * Upload a product photo. Idempotent by content: the same image returns the existing product
 * with 200. The client filename and content type are ignored.
 *
 * When a vision judge is configured the product profile (box, colours, label text as data) is
 * extracted now and stored in `reference_facts`; otherwise it is `unverified` until a run can
 * compute it.
 */
export const productsCreateProduct = <ThrowOnError extends boolean = false>(options: Options<ProductsCreateProductData, ThrowOnError>): RequestResult<ProductsCreateProductResponses, ProductsCreateProductErrors, ThrowOnError> => (options.client ?? client).post<ProductsCreateProductResponses, ProductsCreateProductErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/v1/products',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Product
 */
export const productsGetProduct = <ThrowOnError extends boolean = false>(options: Options<ProductsGetProductData, ThrowOnError>): RequestResult<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError> => (options.client ?? client).get<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError>({ url: '/v1/products/{product_id}', ...options });

/**
 * List Runs
 *
 * Run history, newest first (cursor paging over created_at, id).
 */
export const runsListRuns = <ThrowOnError extends boolean = false>(options?: Options<RunsListRunsData, ThrowOnError>): RequestResult<RunsListRunsResponses, RunsListRunsErrors, ThrowOnError> => (options?.client ?? client).get<RunsListRunsResponses, RunsListRunsErrors, ThrowOnError>({ url: '/v1/runs', ...options });

/**
 * Create Run Route
 *
 * Start a run for a brief. Returns 202 at once; follow `events_url` (SSE) for progress.
 */
export const runsCreateRunRoute = <ThrowOnError extends boolean = false>(options: Options<RunsCreateRunRouteData, ThrowOnError>): RequestResult<RunsCreateRunRouteResponses, RunsCreateRunRouteErrors, ThrowOnError> => (options.client ?? client).post<RunsCreateRunRouteResponses, RunsCreateRunRouteErrors, ThrowOnError>({
    url: '/v1/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Run
 *
 * The authoritative snapshot of a run (reload-safe; the UI rebuilds its timeline from it).
 */
export const runsGetRun = <ThrowOnError extends boolean = false>(options: Options<RunsGetRunData, ThrowOnError>): RequestResult<RunsGetRunResponses, RunsGetRunErrors, ThrowOnError> => (options.client ?? client).get<RunsGetRunResponses, RunsGetRunErrors, ThrowOnError>({ url: '/v1/runs/{run_id}', ...options });

/**
 * Cancel Run
 *
 * Stop an active run: its task is cancelled and the run ends `cancelled`.
 */
export const runsCancelRun = <ThrowOnError extends boolean = false>(options: Options<RunsCancelRunData, ThrowOnError>): RequestResult<RunsCancelRunResponses, RunsCancelRunErrors, ThrowOnError> => (options.client ?? client).post<RunsCancelRunResponses, RunsCancelRunErrors, ThrowOnError>({ url: '/v1/runs/{run_id}/cancel', ...options });

/**
 * Decide Run
 *
 * Human release: approve or reject a `passed` / `needs_review` run (audited).
 *
 * Approving a `needs_review` run overrides the gate: `reason` is required, and the decision is
 * also stored as a human label on the approved image.
 */
export const runsDecideRun = <ThrowOnError extends boolean = false>(options: Options<RunsDecideRunData, ThrowOnError>): RequestResult<RunsDecideRunResponses, RunsDecideRunErrors, ThrowOnError> => (options.client ?? client).post<RunsDecideRunResponses, RunsDecideRunErrors, ThrowOnError>({
    url: '/v1/runs/{run_id}/decision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run Events
 *
 * SSE: replays events with `seq > Last-Event-ID`, then tails until `run.finished`, then closes.
 *
 * Keep-alive comments every 15 s. Works after the run has ended (full replay).
 */
export const runsRunEvents = <ThrowOnError extends boolean = false>(options: Options<RunsRunEventsData, ThrowOnError, unknown>): Promise<ServerSentEventsResult<RunsRunEventsResponses>> => (options.client ?? client).sse.get<RunsRunEventsResponses, RunsRunEventsErrors, ThrowOnError>({ url: '/v1/runs/{run_id}/events', ...options });
