// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AdStudioStatus
 */
export type AdStudioStatus = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Models
     */
    models: Array<ModelRow>;
    ocr: OcrStatus;
    /**
     * Status
     */
    status: 'ok' | 'degraded';
};

/**
 * AgreementMetrics
 */
export type AgreementMetrics = {
    /**
     * Agree
     */
    agree?: number;
    /**
     * Agreement
     */
    agreement?: number | null;
    /**
     * Kappa
     */
    kappa?: number | null;
    /**
     * N
     */
    n?: number;
};

/**
 * Body_products_create_product
 */
export type BodyProductsCreateProduct = {
    /**
     * Image
     *
     * PNG, JPEG or WebP, at most 10 MB
     */
    image: Blob | File;
    /**
     * Name
     */
    name: string;
};

/**
 * BriefView
 */
export type BriefView = {
    /**
     * Aspect Ratio
     */
    aspect_ratio: string;
    /**
     * Geography Code
     */
    geography_code: string;
    /**
     * Geography Detail
     */
    geography_detail: string | null;
    /**
     * Golden Key
     */
    golden_key: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Required Text
     */
    required_text: string;
    /**
     * Season
     */
    season: string;
};

/**
 * BudgetWarningEvent
 */
export type BudgetWarningEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Cap Usd
     */
    cap_usd: number;
    /**
     * Image Calls
     */
    image_calls?: number | null;
    /**
     * Max Image Calls
     */
    max_image_calls?: number | null;
    /**
     * Reason
     */
    reason?: 'threshold' | 'exhausted' | 'deadline';
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Spent Usd
     */
    spent_usd: number;
    /**
     * Type
     */
    type: 'budget.warning';
};

/**
 * CandidateCreatedEvent
 */
export type CandidateCreatedEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Attempt
     */
    attempt: number;
    /**
     * Cached
     */
    cached: boolean;
    /**
     * Candidate Id
     */
    candidate_id: string;
    /**
     * Height
     */
    height: number | null;
    /**
     * Image Id
     */
    image_id: string | null;
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Kind
     */
    kind: 'initial' | 'repair' | 'clean_plate' | 'overlay';
    /**
     * Model
     */
    model: string;
    /**
     * Native Height
     */
    native_height: number | null;
    /**
     * Native Width
     */
    native_width: number | null;
    /**
     * Parent Candidate Id
     *
     * The candidate this one repairs or overlays (lineage)
     */
    parent_candidate_id?: string | null;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Slot
     */
    slot: number;
    /**
     * Status
     */
    status: 'pending' | 'blocked';
    /**
     * Type
     */
    type: 'candidate.created';
    /**
     * Width
     */
    width: number | null;
};

/**
 * CandidateView
 */
export type CandidateView = {
    /**
     * Attempt
     */
    attempt: number;
    /**
     * Created At
     */
    created_at: string;
    evaluation: EvaluationView | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Image Id
     */
    image_id: string | null;
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Parent Candidate Id
     */
    parent_candidate_id: string | null;
    /**
     * Prompt Version
     */
    prompt_version: string | null;
    /**
     * Repair Instruction
     */
    repair_instruction: string | null;
    /**
     * Requested Model
     */
    requested_model: string | null;
    /**
     * Served Model
     */
    served_model: string | null;
    /**
     * Slot
     */
    slot: number;
    /**
     * Status
     */
    status: string;
    /**
     * Width
     */
    width: number | null;
};

/**
 * CheckView
 */
export type CheckView = {
    /**
     * Check Name
     */
    check_name: string;
    /**
     * Dimension
     */
    dimension: string;
    /**
     * Evidence
     */
    evidence: string | null;
    /**
     * Evidence Data
     */
    evidence_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Method
     */
    method: string;
    /**
     * Passed
     */
    passed: boolean | null;
    /**
     * Threshold
     */
    threshold: number | null;
    /**
     * Value
     */
    value: number | null;
};

/**
 * CompleteRequest
 */
export type CompleteRequest = {
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * CompleteResponse
 */
export type CompleteResponse = {
    /**
     * Cached
     */
    cached: boolean;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Model
     */
    model: string;
    /**
     * Request Id
     */
    request_id: string | null;
    /**
     * Text
     */
    text: string;
};

/**
 * Confusion
 */
export type Confusion = {
    /**
     * Fn
     */
    fn?: number;
    /**
     * Fp
     */
    fp?: number;
    /**
     * Tn
     */
    tn?: number;
    /**
     * Tp
     */
    tp?: number;
};

/**
 * Criterion
 */
export type Criterion = {
    /**
     * Baseline
     */
    baseline?: number | null;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Id
     */
    id: string;
    /**
     * Met
     */
    met?: boolean | null;
    /**
     * Metric
     */
    metric: string;
    /**
     * Note
     */
    note?: string;
    /**
     * Now
     */
    now?: number | null;
    /**
     * Target
     */
    target: string;
};

/**
 * DecisionCreate
 *
 * A human release decision; approving a `needs_review` run is an override (needs a reason).
 */
export type DecisionCreate = {
    /**
     * Action
     */
    action: 'approve' | 'reject';
    /**
     * Actor
     *
     * Who decides; recorded in the audit row and as labeller human:<actor>
     */
    actor?: string;
    /**
     * Reason
     *
     * Required to approve a needs_review run (an override of the gate)
     */
    reason?: string | null;
};

/**
 * DecisionView
 */
export type DecisionView = {
    /**
     * Action
     */
    action: 'approve' | 'reject';
    /**
     * Actor
     */
    actor: string;
    /**
     * Approved Candidate Id
     */
    approved_candidate_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Override
     */
    is_override: boolean;
    /**
     * Label Id
     *
     * The labels row an override wrote (labeller human:<actor>)
     */
    label_id?: string | null;
    /**
     * Previous Status
     */
    previous_status: string;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: 'approved' | 'rejected';
};

/**
 * DimensionMetrics
 */
export type DimensionMetrics = {
    confusion?: Confusion;
    /**
     * F1
     */
    f1?: number | null;
    /**
     * N
     */
    n?: number;
    /**
     * Not Assessed
     *
     * Items where this dimension was not evaluated (technical failed)
     */
    not_assessed?: number;
    /**
     * Precision
     */
    precision?: number | null;
    /**
     * Recall
     */
    recall?: number | null;
    /**
     * Unlabelled
     */
    unlabelled?: number;
};

/**
 * DimensionSummary
 */
export type DimensionSummary = {
    confusion: Confusion;
    /**
     * F1
     */
    f1: number | null;
    /**
     * N
     */
    n: number;
    /**
     * Precision
     */
    precision: number | null;
    /**
     * Recall
     */
    recall: number | null;
};

/**
 * DimensionView
 */
export type DimensionView = {
    /**
     * Passed
     *
     * null = unverified
     */
    passed: boolean | null;
    /**
     * Reasons
     */
    reasons?: Array<string>;
};

/**
 * DoneEvent
 */
export type DoneEvent = {
    /**
     * Cached
     */
    cached: boolean;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Model
     */
    model: string | null;
    /**
     * Type
     */
    type: 'done';
};

/**
 * ErrorEvent
 */
export type ErrorEvent = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Type
     */
    type: 'error';
};

/**
 * EvalItem
 *
 * One labelled item with its evaluator verdict (planted-failure gallery and drill-down).
 */
export type EvalItem = {
    /**
     * Aspect Ratio
     */
    aspect_ratio?: string | null;
    /**
     * Brief Id
     */
    brief_id: string;
    /**
     * Dimensions
     */
    dimensions: {
        [key: string]: boolean | null;
    };
    /**
     * Evidence
     */
    evidence: Array<string>;
    /**
     * Geography Code
     *
     * From data/golden/briefs.yaml
     */
    geography_code?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Image Id
     */
    image_id: string | null;
    /**
     * Image Url
     */
    image_url: string | null;
    /**
     * Label
     */
    label: {
        [key: string]: boolean | null;
    } | null;
    /**
     * Label Source
     */
    label_source: string;
    /**
     * Mutation
     */
    mutation: string | null;
    /**
     * Origin
     */
    origin: 'natural' | 'planted';
    /**
     * Outcomes
     */
    outcomes: {
        [key: string]: 'tp' | 'fp' | 'fn' | 'tn' | null;
    };
    /**
     * Product Id
     *
     * Golden product key (P1..P5)
     */
    product_id: string;
    /**
     * Product Name
     */
    product_name?: string | null;
    /**
     * Required Text
     */
    required_text?: string | null;
    /**
     * Run Id
     *
     * The golden run that produced this image (natural items)
     */
    run_id?: string | null;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Set
     */
    set: 'nat' | 'final' | 'plant';
    /**
     * Source Image Url
     */
    source_image_url: string | null;
    /**
     * Split
     */
    split: 'calibration' | 'heldout';
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Verdict
     */
    verdict: 'pass' | 'fail' | 'unverified';
};

/**
 * EvalProvenance
 *
 * Where the report's numbers come from (docs/ux.md `ReportProvenance`).
 */
export type EvalProvenance = {
    /**
     * Assume Pass Labels
     */
    assume_pass_labels?: boolean;
    /**
     * Evaluator Version
     */
    evaluator_version?: string;
    /**
     * Git Sha
     */
    git_sha?: string | null;
    /**
     * Image Clients
     */
    image_clients?: Array<string>;
    /**
     * Image Models
     */
    image_models?: Array<string>;
    /**
     * Image Prompt Versions
     *
     * `ad_generate`/`ad_repair` versions in the outputs
     */
    image_prompt_versions?: Array<string>;
    /**
     * Judge Client
     *
     * Vision judge client (fake|google)
     */
    judge_client?: string | null;
    /**
     * Judge Model
     */
    judge_model?: string | null;
    /**
     * Network Attempts
     */
    network_attempts?: number | null;
    /**
     * Ocr Engine
     */
    ocr_engine?: string | null;
    /**
     * Ocr Languages
     *
     * Tesseract language packs installed when the verdict snapshot was recorded
     */
    ocr_languages?: Array<string>;
    /**
     * Ocr Version
     */
    ocr_version?: string | null;
    /**
     * Prompt Versions
     *
     * Evaluator prompt name -> version
     */
    prompt_versions?: {
        [key: string]: string;
    };
    /**
     * Snapshot Entries
     */
    snapshot_entries?: number | null;
    /**
     * Snapshot Evaluator Version
     */
    snapshot_evaluator_version?: string | null;
    /**
     * Snapshot File
     *
     * Verdict snapshot file name
     */
    snapshot_file?: string | null;
    /**
     * Snapshot Recorded At
     */
    snapshot_recorded_at?: string | null;
};

/**
 * EvalSummary
 *
 * The latest eval report (architecture API contract `EvalSummary`, plus the PRD criteria).
 */
export type EvalSummary = {
    /**
     * After Repair Pass Rate
     */
    after_repair_pass_rate: number | null;
    /**
     * Agreement By Dimension
     *
     * Human agreement per image set (nat|final) and dimension, with Cohen's kappa
     */
    agreement_by_dimension?: {
        [key: string]: {
            [key: string]: AgreementMetrics;
        };
    };
    /**
     * v1 -> v2: human and evaluator pass rates per dimension (incl. composition) and evaluator P/R per version; on the newest version's report
     */
    comparison?: GoldenComparison | null;
    /**
     * Cost Per Approved Ad
     */
    cost_per_approved_ad: number | null;
    /**
     * Counts
     */
    counts: {
        [key: string]: number;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Criteria
     */
    criteria: Array<Criterion>;
    /**
     * Dataset Version
     */
    dataset_version: string;
    /**
     * Dry Run
     */
    dry_run: boolean;
    /**
     * Evaluator Version
     */
    evaluator_version: string;
    /**
     * First Attempt Pass Rate
     */
    first_attempt_pass_rate: number | null;
    /**
     * Git Sha
     */
    git_sha: string | null;
    /**
     * Golden Version
     *
     * Golden dataset version (v1 | v2) of this report
     */
    golden_version?: string | null;
    hemisphere?: RateMetric;
    /**
     * Human Agreement
     */
    human_agreement: number | null;
    /**
     * Human Agreement N
     */
    human_agreement_n: number;
    /**
     * Human Kappa
     */
    human_kappa: number | null;
    /**
     * Judge Stability Flip Rate
     */
    judge_stability_flip_rate: number | null;
    known_good: RateMetric;
    /**
     * Native Text Rate
     */
    native_text_rate: number | null;
    /**
     * P50 Latency To Approved Ms
     */
    p50_latency_to_approved_ms: number | null;
    /**
     * P95 Latency To Approved Ms
     */
    p95_latency_to_approved_ms: number | null;
    /**
     * Per Dimension
     */
    per_dimension: {
        [key: string]: DimensionSummary;
    };
    /**
     * Per Split
     */
    per_split: {
        [key: string]: {
            [key: string]: DimensionSummary;
        };
    };
    /**
     * Pipeline quality on the golden runs: mean_repairs, status_counts (runs by status), pass rates, cost and latency
     */
    pipeline?: PipelineMetrics;
    /**
     * Planted
     */
    planted: Array<PlantedClassMetrics>;
    provenance?: EvalProvenance;
    /**
     * Report File
     */
    report_file: string;
    /**
     * Report Id
     */
    report_id: string;
    stability?: StabilityMetrics;
    /**
     * Targets
     */
    targets: {
        [key: string]: string;
    };
    /**
     * Text Exact Rate
     */
    text_exact_rate: number | null;
    /**
     * Warnings
     *
     * FAKE DRY RUN, missing labels, stale snapshot/report and the report's own
     */
    warnings?: Array<string>;
};

/**
 * EvaluationDoneEvent
 */
export type EvaluationDoneEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Candidate Id
     */
    candidate_id: string;
    /**
     * Dimensions
     */
    dimensions: {
        [key: string]: DimensionView;
    };
    /**
     * Evaluation Id
     */
    evaluation_id: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Type
     */
    type: 'evaluation.done';
    /**
     * Verdict
     */
    verdict: 'pass' | 'fail' | 'unverified';
};

/**
 * EvaluationView
 */
export type EvaluationView = {
    /**
     * Checks
     */
    checks: Array<CheckView>;
    /**
     * Dimensions
     */
    dimensions: {
        [key: string]: boolean | null;
    };
    /**
     * Evaluator Version
     */
    evaluator_version: string;
    /**
     * Id
     */
    id: string;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Overall Pass
     */
    overall_pass: boolean;
    /**
     * Verdict
     */
    verdict: string;
};

/**
 * FallbackAppliedEvent
 */
export type FallbackAppliedEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Candidate Id
     */
    candidate_id: string;
    /**
     * From Candidate Id
     */
    from_candidate_id?: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Type
     */
    type: 'fallback.applied';
    /**
     * Verification
     *
     * How the overlaid text was verified (ai-design §4.4 step 5)
     */
    verification?: 'ocr' | 'construction' | 'failed' | null;
};

/**
 * GoldenComparison
 *
 * v1 (baseline, orchestrator-3) vs v2 (ADR-007, orchestrator-4), in version order.
 */
export type GoldenComparison = {
    /**
     * Versions
     */
    versions: Array<VersionSummary>;
};

/**
 * GoldenProductSource
 */
export type GoldenProductSource = {
    /**
     * Author
     */
    author: string;
    /**
     * File
     */
    file: string;
    /**
     * Id
     *
     * Golden product key (P1..P5)
     */
    id: string;
    /**
     * Licence
     */
    licence: string;
    /**
     * Licence Url
     */
    licence_url: string | null;
    /**
     * Name
     *
     * Product name from briefs.yaml
     */
    name?: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Share Alike
     */
    share_alike: boolean;
    /**
     * Source Title
     */
    source_title: string;
    /**
     * Source Url
     */
    source_url: string | null;
};

/**
 * GoldenSources
 */
export type GoldenSources = {
    /**
     * Markdown
     *
     * SOURCES.md verbatim (render as markdown)
     */
    markdown: string;
    /**
     * Path
     *
     * Repository path of the sources file
     */
    path: string;
    /**
     * Products
     */
    products: Array<GoldenProductSource>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status?: 'ok';
};

/**
 * ModelRow
 */
export type ModelRow = {
    /**
     * Breaker
     */
    breaker?: string;
    /**
     * Client
     *
     * gemini | fake
     */
    client: string;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Recorded As
     *
     * The model id calls are recorded under in the ledger
     */
    recorded_as: string;
    /**
     * Role
     */
    role: 'image_candidate' | 'image_repair' | 'vision_judge';
    /**
     * Spec
     *
     * The configured model (IMAGE_MODEL_* / VISION_JUDGE)
     */
    spec: string;
};

/**
 * NormBoxView
 */
export type NormBoxView = {
    /**
     * X0
     */
    x0: number;
    /**
     * X1
     */
    x1: number;
    /**
     * Y0
     */
    y0: number;
    /**
     * Y1
     */
    y1: number;
};

/**
 * OcrStatus
 */
export type OcrStatus = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Engine
     */
    engine: string;
    /**
     * Languages
     *
     * Installed Tesseract language packs
     */
    languages: number;
    /**
     * Scripts
     *
     * Scripts with an OCR pack (others are verified by construction after overlay)
     */
    scripts: {
        [key: string]: boolean;
    };
    /**
     * Shaping
     *
     * libraqm available for complex-script overlay
     */
    shaping: boolean;
    /**
     * Version
     */
    version: string;
};

/**
 * OpsSummary
 */
export type OpsSummary = {
    /**
     * Avg Cost Usd
     */
    avg_cost_usd: number | null;
    /**
     * By Kind
     */
    by_kind: {
        [key: string]: number;
    };
    /**
     * Cache Hit Rate
     */
    cache_hit_rate: number | null;
    /**
     * Count
     */
    count: number;
    /**
     * Error Rate
     */
    error_rate: number | null;
    /**
     * Fallback Rate
     */
    fallback_rate: number | null;
    /**
     * P50 Latency Ms
     */
    p50_latency_ms: number | null;
    /**
     * P95 Latency Ms
     */
    p95_latency_ms: number | null;
    /**
     * Run metrics over the most recent `run_window` runs
     */
    runs?: RunMetrics | null;
    /**
     * Total Cost Usd
     */
    total_cost_usd: number;
    /**
     * Window
     */
    window: number;
};

/**
 * Page[EvalItem]
 */
export type PageEvalItem = {
    /**
     * Items
     */
    items: Array<EvalItem>;
    /**
     * Next Cursor
     *
     * Opaque; pass as `cursor` to get the next page.
     */
    next_cursor?: string | null;
};

/**
 * Page[Product]
 */
export type PageProduct = {
    /**
     * Items
     */
    items: Array<Product>;
    /**
     * Next Cursor
     *
     * Opaque; pass as `cursor` to get the next page.
     */
    next_cursor?: string | null;
};

/**
 * Page[RunSummary]
 */
export type PageRunSummary = {
    /**
     * Items
     */
    items: Array<RunSummary>;
    /**
     * Next Cursor
     *
     * Opaque; pass as `cursor` to get the next page.
     */
    next_cursor?: string | null;
};

/**
 * PipelineMetrics
 */
export type PipelineMetrics = {
    /**
     * After Repair Pass Rate
     */
    after_repair_pass_rate?: number | null;
    /**
     * Briefs
     */
    briefs?: number;
    /**
     * Cost Per Approved Ad
     */
    cost_per_approved_ad?: number | null;
    /**
     * First Attempt Pass Rate
     */
    first_attempt_pass_rate?: number | null;
    /**
     * Hue Drift By Product
     */
    hue_drift_by_product?: {
        [key: string]: number;
    };
    /**
     * Hue Drift N
     */
    hue_drift_n?: number;
    /**
     * Hue Drift Rate
     */
    hue_drift_rate?: number | null;
    /**
     * Images Checked
     */
    images_checked?: number;
    /**
     * Mean Repairs
     */
    mean_repairs?: number | null;
    /**
     * Minor Label Detail N
     */
    minor_label_detail_n?: number;
    /**
     * Minor Label Detail Rate
     */
    minor_label_detail_rate?: number | null;
    /**
     * Native Text N
     */
    native_text_n?: number;
    /**
     * Native Text Rate
     */
    native_text_rate?: number | null;
    /**
     * P50 Latency Ms
     */
    p50_latency_ms?: number | null;
    /**
     * P95 Latency Ms
     */
    p95_latency_ms?: number | null;
    /**
     * Resolution Ok Rate
     */
    resolution_ok_rate?: number | null;
    /**
     * Shipped
     */
    shipped?: number;
    /**
     * Status Counts
     */
    status_counts?: {
        [key: string]: number;
    };
    /**
     * Text Exact Construction
     */
    text_exact_construction?: number;
    /**
     * Text Exact Ocr
     */
    text_exact_ocr?: number;
    /**
     * Text Exact Rate
     */
    text_exact_rate?: number | null;
    /**
     * Total Cost Usd
     */
    total_cost_usd?: number;
};

/**
 * PlanDoneEvent
 */
export type PlanDoneEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    spec_summary: SpecSummary;
    /**
     * Type
     */
    type: 'plan.done';
};

/**
 * PlantedClassMetrics
 */
export type PlantedClassMetrics = {
    /**
     * Caught
     */
    caught: number;
    /**
     * Expected
     */
    expected: Array<string>;
    /**
     * Missed
     */
    missed?: Array<string>;
    /**
     * Mutation
     */
    mutation: string;
    /**
     * N
     */
    n: number;
    /**
     * Rate
     */
    rate: number | null;
};

/**
 * Product
 */
export type Product = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Facts Version
     */
    facts_version?: string | null;
    /**
     * Height
     */
    height: number;
    /**
     * Id
     */
    id: string;
    /**
     * Image Id
     */
    image_id: string;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Name
     */
    name: string;
    /**
     * Reference Facts
     *
     * Vision product profile; null until it has been extracted.
     */
    reference_facts?: {
        [key: string]: unknown;
    } | null;
    /**
     * Width
     */
    width: number;
};

/**
 * ProductScaleView
 *
 * ADR-007: how big the product should be (its longest side / the image height).
 */
export type ProductScaleView = {
    /**
     * Framing
     *
     * close_up | medium | wide
     */
    framing: string;
    /**
     * Resting Surface
     */
    resting_surface?: string | null;
    /**
     * Scale Max
     */
    scale_max: number;
    /**
     * Scale Min
     */
    scale_min: number;
    /**
     * Scale References
     */
    scale_references?: Array<string>;
    /**
     * Size Class
     */
    size_class: string;
    /**
     * Size Cm
     *
     * The product's real-world largest dimension
     */
    size_cm: number;
};

/**
 * ProviderStatus
 */
export type ProviderStatus = {
    /**
     * Breaker
     */
    breaker?: string;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Provider
     */
    provider: string;
    /**
     * Role
     */
    role: string;
    /**
     * Spec
     */
    spec: string;
};

/**
 * RateMetric
 */
export type RateMetric = {
    /**
     * N
     */
    n?: number;
    /**
     * Ok
     */
    ok?: number;
    /**
     * Rate
     */
    rate?: number | null;
};

/**
 * ReadyResponse
 */
export type ReadyResponse = {
    /**
     * Image-model, vision-judge and OCR rows for the status page
     */
    adstudio?: AdStudioStatus | null;
    /**
     * Db
     */
    db: boolean;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Extensions
     */
    extensions: {
        [key: string]: boolean;
    };
    /**
     * Providers
     */
    providers: Array<ProviderStatus>;
    /**
     * Status
     */
    status: 'ok' | 'degraded' | 'unavailable';
};

/**
 * RepairStartedEvent
 */
export type RepairStartedEvent = {
    /**
     * Action
     *
     * regenerate | repair_product | repair_context | repair_composition | repair_text | clean_plate
     */
    action?: string | null;
    /**
     * At
     */
    at: string;
    /**
     * Attempt
     */
    attempt?: number | null;
    /**
     * From Candidate Id
     */
    from_candidate_id: string;
    /**
     * Instruction
     *
     * Summary of the edit (code-built, never VLM prose)
     */
    instruction: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Row
     *
     * Routing-table row (ai-design §4.3)
     */
    row?: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Target Dimension
     */
    target_dimension: 'technical' | 'text' | 'product' | 'context' | 'composition';
    /**
     * Type
     */
    type: 'repair.started';
};

/**
 * ResultEvent
 */
export type ResultEvent = {
    /**
     * Data
     */
    data: unknown;
    /**
     * Type
     */
    type: 'result';
};

/**
 * RunAccepted
 */
export type RunAccepted = {
    /**
     * Brief Id
     */
    brief_id: string;
    /**
     * Events Url
     */
    events_url: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Run Url
     */
    run_url: string;
    /**
     * Status
     */
    status: string;
};

/**
 * RunCancelled
 */
export type RunCancelled = {
    /**
     * Cancelled
     *
     * False when the run ended on its own first
     */
    cancelled: boolean;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * RunCreate
 *
 * A brief to run. `required_text` is rendered exactly as given (after NFC).
 */
export type RunCreate = {
    /**
     * Aspect Ratio
     */
    aspect_ratio?: '1:1' | '4:5';
    /**
     * Fresh
     *
     * Salt the image cache so a repeat makes new images
     */
    fresh?: boolean;
    /**
     * Geography Code
     *
     * ISO 3166-1 alpha-2 country code
     */
    geography_code: string;
    /**
     * Geography Detail
     *
     * Optional region or city (alias table only)
     */
    geography_detail?: string | null;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Required Text
     *
     * 1-80 characters, at most 3 lines
     */
    required_text: string;
    /**
     * Season
     *
     * Month, season name or holiday, e.g. December
     */
    season: string;
};

/**
 * RunDetail
 */
export type RunDetail = {
    /**
     * Approved Candidate Id
     */
    approved_candidate_id: string | null;
    /**
     * Best Candidate Id
     *
     * The candidate to review: the approved one, or the best one on needs_review
     */
    best_candidate_id?: string | null;
    brief: BriefView;
    /**
     * Candidates
     */
    candidates: Array<CandidateView>;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Events Url
     */
    events_url: string;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Product Id
     */
    product_id: string;
    run: RunView;
    /**
     * Spec
     */
    spec: {
        [key: string]: unknown;
    } | null;
    /**
     * Spec Version
     */
    spec_version: string | null;
};

/**
 * RunErrorEvent
 */
export type RunErrorEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Problem
     */
    problem: {
        [key: string]: unknown;
    };
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Type
     */
    type: 'run.error';
};

/**
 * RunFinishedEvent
 */
export type RunFinishedEvent = {
    /**
     * Approved Candidate Id
     */
    approved_candidate_id: string | null;
    /**
     * At
     */
    at: string;
    /**
     * Best Candidate Id
     *
     * needs_review: the candidate shown for the human decision
     */
    best_candidate_id?: string | null;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Outcome
     */
    outcome: 'native' | 'overlay' | null;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Status
     */
    status: 'passed' | 'needs_review' | 'failed' | 'interrupted' | 'cancelled';
    /**
     * Type
     */
    type: 'run.finished';
};

/**
 * RunMetrics
 *
 * Run numbers over the most recent `window` runs (architecture "Observability").
 */
export type RunMetrics = {
    /**
     * Active
     */
    active?: number;
    /**
     * Approved
     *
     * Runs a human approved
     */
    approved: number;
    /**
     * Approved Rate
     *
     * approved / finished
     */
    approved_rate: number | null;
    /**
     * By Status
     */
    by_status: {
        [key: string]: number;
    };
    /**
     * Cost Per Approved Ad
     *
     * Spend of every finished run / approved runs
     */
    cost_per_approved_ad: number | null;
    /**
     * Cost Per Gate Pass
     *
     * Spend of every finished run / runs whose gate passed
     */
    cost_per_gate_pass: number | null;
    /**
     * Count
     *
     * Runs in the window
     */
    count: number;
    /**
     * Dimension Pass Rates
     *
     * Per dimension (technical, text, product, context, composition): passing / judged candidate evaluations of the window's runs (unverified and older evaluations without the dimension are left out)
     */
    dimension_pass_rates?: {
        [key: string]: number | null;
    };
    /**
     * Finished
     *
     * Runs that reached a terminal or decided status
     */
    finished: number;
    /**
     * First Attempt Pass Rate
     *
     * A first-round candidate passed / runs with candidates
     */
    first_attempt_pass_rate: number | null;
    /**
     * Gate Pass Rate
     *
     * Runs whose gate passed a candidate (outcome set) / finished
     */
    gate_pass_rate: number | null;
    /**
     * Mean Repairs
     */
    mean_repairs: number | null;
    /**
     * Overlay Rate
     *
     * outcome overlay / runs with an outcome
     */
    overlay_rate: number | null;
    /**
     * Override Count
     *
     * Approved runs the gate had held (needs_review)
     */
    override_count: number;
    /**
     * P50 Ms To Approved
     *
     * Pipeline latency (run created -> gate passed) of gate-passed runs, p50
     */
    p50_ms_to_approved: number | null;
    /**
     * P95 Ms To Approved
     */
    p95_ms_to_approved: number | null;
    /**
     * Queued
     */
    queued?: number;
    /**
     * Total Cost Usd
     */
    total_cost_usd: number;
    /**
     * Window
     */
    window: number;
};

/**
 * RunStatusEvent
 */
export type RunStatusEvent = {
    /**
     * At
     */
    at: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     *
     * Per-run sequence; the SSE `id:`
     */
    seq: number;
    /**
     * Status
     */
    status: 'queued' | 'planning' | 'generating' | 'evaluating' | 'repairing' | 'fallback' | 'passed' | 'needs_review' | 'failed' | 'interrupted' | 'cancelled' | 'approved' | 'rejected';
    /**
     * Type
     */
    type: 'run.status';
};

/**
 * RunSummary
 */
export type RunSummary = {
    /**
     * Approved Candidate Id
     */
    approved_candidate_id: string | null;
    /**
     * Aspect Ratio
     */
    aspect_ratio: string;
    /**
     * Best Candidate Id
     */
    best_candidate_id: string | null;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * First Attempt Pass
     */
    first_attempt_pass: boolean | null;
    /**
     * Geography Code
     */
    geography_code: string;
    /**
     * Golden Key
     */
    golden_key: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Origin
     */
    origin: string;
    /**
     * Outcome
     */
    outcome: string | null;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Repair Count
     */
    repair_count: number;
    /**
     * Required Text
     */
    required_text: string;
    /**
     * Season
     */
    season: string;
    /**
     * Status
     */
    status: string;
    /**
     * Thumbnail Url
     *
     * The approved candidate's image, else the best candidate's
     */
    thumbnail_url: string | null;
};

/**
 * RunView
 */
export type RunView = {
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error
     */
    error: {
        [key: string]: unknown;
    } | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * First Attempt Pass
     */
    first_attempt_pass: boolean | null;
    /**
     * Id
     */
    id: string;
    /**
     * Latency Ms
     */
    latency_ms: number | null;
    /**
     * Origin
     */
    origin: string;
    /**
     * Outcome
     */
    outcome: string | null;
    /**
     * Repair Count
     */
    repair_count: number;
    /**
     * Status
     */
    status: string;
};

/**
 * SpecSummary
 */
export type SpecSummary = {
    /**
     * Avoid
     */
    avoid?: Array<string>;
    /**
     * Country Name
     */
    country_name?: string | null;
    /**
     * Effective Season
     */
    effective_season?: string | null;
    /**
     * Hemisphere
     */
    hemisphere?: string | null;
    /**
     * Holidays
     */
    holidays?: Array<string>;
    /**
     * Locale Cues
     */
    locale_cues?: Array<string>;
    /**
     * Months
     */
    months?: Array<number>;
    /**
     * Planner Model
     */
    planner_model?: string | null;
    /**
     * Framing and product scale (null when the size is unknown)
     */
    product_scale?: ProductScaleView | null;
    /**
     * Rationale
     */
    rationale?: string | null;
    /**
     * Source
     */
    source: 'template' | 'planner' | 'default_table';
    /**
     * Text Lines
     */
    text_lines?: Array<string>;
    /**
     * Text Mode
     */
    text_mode?: 'native' | 'overlay_only';
    text_zone?: NormBoxView | null;
};

/**
 * StabilityMetrics
 */
export type StabilityMetrics = {
    /**
     * Available
     */
    available?: boolean;
    /**
     * Checks
     */
    checks?: number;
    /**
     * Flip Rate
     */
    flip_rate?: number | null;
    /**
     * Flips
     */
    flips?: number;
    /**
     * Items
     */
    items?: number;
};

/**
 * StatusEvent
 */
export type StatusEvent = {
    /**
     * Message
     */
    message: string;
    /**
     * Type
     */
    type: 'status';
};

/**
 * StepEvent
 */
export type StepEvent = {
    /**
     * Detail
     */
    detail: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * State
     */
    state: 'started' | 'done' | 'failed' | 'skipped';
    /**
     * Type
     */
    type: 'step';
};

/**
 * TokenEvent
 */
export type TokenEvent = {
    /**
     * Text
     */
    text: string;
    /**
     * Type
     */
    type: 'token';
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersionSummary
 *
 * One golden version's headline numbers for the v1 -> v2 comparison (ADR-007).
 */
export type VersionSummary = {
    /**
     * After Repair Pass Rate
     */
    after_repair_pass_rate?: number | null;
    /**
     * Cost Per Approved Ad
     */
    cost_per_approved_ad?: number | null;
    /**
     * Counts
     */
    counts?: {
        [key: string]: number;
    };
    /**
     * Evaluator Pass Rates
     *
     * set (nat|final) -> dimension -> share of images the evaluator passes
     */
    evaluator_pass_rates?: {
        [key: string]: {
            [key: string]: RateMetric;
        };
    };
    /**
     * Evaluator Version
     */
    evaluator_version: string;
    /**
     * First Attempt Pass Rate
     */
    first_attempt_pass_rate?: number | null;
    human_agreement?: AgreementMetrics;
    /**
     * Human Pass Rates
     *
     * set (nat|final) -> dimension -> share of human-labelled images passing
     */
    human_pass_rates?: {
        [key: string]: {
            [key: string]: RateMetric;
        };
    };
    /**
     * Per Dimension
     */
    per_dimension?: {
        [key: string]: DimensionMetrics;
    };
    /**
     * Pipeline Versions
     */
    pipeline_versions?: Array<string>;
    /**
     * Version
     */
    version: string;
};

export type HealthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthResponse = HealthHealthResponses[keyof HealthHealthResponses];

export type HealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type HealthReadyErrors = {
    /**
     * Service Unavailable
     */
    503: ReadyResponse;
};

export type HealthReadyError = HealthReadyErrors[keyof HealthReadyErrors];

export type HealthReadyResponses = {
    /**
     * Successful Response
     */
    200: ReadyResponse;
};

export type HealthReadyResponse = HealthReadyResponses[keyof HealthReadyResponses];

export type EvalsEvalItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Origin
         */
        origin?: 'natural' | 'planted' | null;
        /**
         * Dimension
         */
        dimension?: 'technical' | 'text' | 'product' | 'context' | 'composition' | null;
        /**
         * Outcome
         */
        outcome?: 'tp' | 'fp' | 'fn' | 'tn' | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         *
         * `next_cursor` of the previous page
         */
        cursor?: string | null;
        /**
         * Golden Version
         *
         * Golden dataset version (v1 | v2); default: the newest report of any version
         */
        golden_version?: string | null;
    };
    url: '/v1/evals/items';
};

export type EvalsEvalItemsErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
};

export type EvalsEvalItemsResponses = {
    /**
     * Successful Response
     */
    200: PageEvalItem;
};

export type EvalsEvalItemsResponse = EvalsEvalItemsResponses[keyof EvalsEvalItemsResponses];

export type EvalsEvalSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Evaluator Version
         */
        evaluator_version?: string | null;
        /**
         * Golden Version
         *
         * Golden dataset version (v1 | v2); default: the newest report of any version
         */
        golden_version?: string | null;
    };
    url: '/v1/evals/summary';
};

export type EvalsEvalSummaryErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvalsEvalSummaryError = EvalsEvalSummaryErrors[keyof EvalsEvalSummaryErrors];

export type EvalsEvalSummaryResponses = {
    /**
     * Successful Response
     */
    200: EvalSummary;
};

export type EvalsEvalSummaryResponse = EvalsEvalSummaryResponses[keyof EvalsEvalSummaryResponses];

export type GoldenGoldenSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/golden/sources';
};

export type GoldenGoldenSourcesErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GoldenGoldenSourcesResponses = {
    /**
     * Successful Response
     */
    200: GoldenSources;
};

export type GoldenGoldenSourcesResponse = GoldenGoldenSourcesResponses[keyof GoldenGoldenSourcesResponses];

export type ImagesGetImageData = {
    body?: never;
    headers?: {
        /**
         * If-None-Match
         */
        'if-none-match'?: string | null;
    };
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/v1/images/{image_id}';
};

export type ImagesGetImageErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesGetImageError = ImagesGetImageErrors[keyof ImagesGetImageErrors];

export type ImagesGetImageResponses = {
    /**
     * Image bytes
     */
    200: unknown;
};

export type LlmCompleteData = {
    body: CompleteRequest;
    path?: never;
    query?: never;
    url: '/v1/llm/complete';
};

export type LlmCompleteErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmCompleteError = LlmCompleteErrors[keyof LlmCompleteErrors];

export type LlmCompleteResponses = {
    /**
     * Successful Response
     */
    200: CompleteResponse;
};

export type LlmCompleteResponse = LlmCompleteResponses[keyof LlmCompleteResponses];

export type LlmStreamData = {
    body: CompleteRequest;
    path?: never;
    query?: never;
    url: '/v1/llm/stream';
};

export type LlmStreamErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmStreamError = LlmStreamErrors[keyof LlmStreamErrors];

export type LlmStreamResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LlmStreamResponse = LlmStreamResponses[keyof LlmStreamResponses];

export type MetaRunEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/meta/run-events';
};

export type MetaRunEventsResponses = {
    /**
     * Response Meta Run Events
     *
     * Successful Response
     */
    200: Array<RunStatusEvent | PlanDoneEvent | CandidateCreatedEvent | EvaluationDoneEvent | RepairStartedEvent | FallbackAppliedEvent | BudgetWarningEvent | RunFinishedEvent | RunErrorEvent>;
};

export type MetaRunEventsResponse = MetaRunEventsResponses[keyof MetaRunEventsResponses];

export type MetaStreamEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/meta/stream-events';
};

export type MetaStreamEventsResponses = {
    /**
     * Response Meta Stream Events
     *
     * Successful Response
     */
    200: Array<StatusEvent | TokenEvent | StepEvent | ResultEvent | ErrorEvent | DoneEvent>;
};

export type MetaStreamEventsResponse = MetaStreamEventsResponses[keyof MetaStreamEventsResponses];

export type OpsSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window
         */
        window?: number;
        /**
         * Run Window
         */
        run_window?: number;
    };
    url: '/v1/ops/summary';
};

export type OpsSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpsSummaryError = OpsSummaryErrors[keyof OpsSummaryErrors];

export type OpsSummaryResponses = {
    /**
     * Successful Response
     */
    200: OpsSummary;
};

export type OpsSummaryResponse = OpsSummaryResponses[keyof OpsSummaryResponses];

export type ProductsListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/v1/products';
};

export type ProductsListProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsListProductsError = ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
    /**
     * Successful Response
     */
    200: PageProduct;
};

export type ProductsListProductsResponse = ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type ProductsCreateProductData = {
    body: BodyProductsCreateProduct;
    path?: never;
    query?: never;
    url: '/v1/products';
};

export type ProductsCreateProductErrors = {
    /**
     * Content Too Large
     */
    413: unknown;
    /**
     * Unsupported Media Type
     */
    415: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
};

export type ProductsCreateProductResponses = {
    /**
     * The same image was uploaded before
     */
    200: Product;
    /**
     * Successful Response
     */
    201: Product;
};

export type ProductsCreateProductResponse = ProductsCreateProductResponses[keyof ProductsCreateProductResponses];

export type ProductsGetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/v1/products/{product_id}';
};

export type ProductsGetProductErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsGetProductError = ProductsGetProductErrors[keyof ProductsGetProductErrors];

export type ProductsGetProductResponses = {
    /**
     * Successful Response
     */
    200: Product;
};

export type ProductsGetProductResponse = ProductsGetProductResponses[keyof ProductsGetProductResponses];

export type RunsListRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Origin
         */
        origin?: 'ui' | 'golden' | null;
        /**
         * Status
         */
        status?: 'queued' | 'planning' | 'generating' | 'evaluating' | 'repairing' | 'fallback' | 'passed' | 'needs_review' | 'failed' | 'interrupted' | 'cancelled' | 'approved' | 'rejected' | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         *
         * `next_cursor` of the previous page
         */
        cursor?: string | null;
    };
    url: '/v1/runs';
};

export type RunsListRunsErrors = {
    /**
     * Unprocessable Content
     */
    422: unknown;
};

export type RunsListRunsResponses = {
    /**
     * Successful Response
     */
    200: PageRunSummary;
};

export type RunsListRunsResponse = RunsListRunsResponses[keyof RunsListRunsResponses];

export type RunsCreateRunRouteData = {
    body: RunCreate;
    headers: {
        /**
         * Idempotency-Key
         *
         * Required. The same key and body return the original run.
         */
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/runs';
};

export type RunsCreateRunRouteErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type RunsCreateRunRouteResponses = {
    /**
     * Replay of the same Idempotency-Key and body
     */
    200: RunAccepted;
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type RunsCreateRunRouteResponse = RunsCreateRunRouteResponses[keyof RunsCreateRunRouteResponses];

export type RunsGetRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}';
};

export type RunsGetRunErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunsGetRunError = RunsGetRunErrors[keyof RunsGetRunErrors];

export type RunsGetRunResponses = {
    /**
     * Successful Response
     */
    200: RunDetail;
};

export type RunsGetRunResponse = RunsGetRunResponses[keyof RunsGetRunResponses];

export type RunsCancelRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}/cancel';
};

export type RunsCancelRunErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunsCancelRunError = RunsCancelRunErrors[keyof RunsCancelRunErrors];

export type RunsCancelRunResponses = {
    /**
     * Successful Response
     */
    200: RunCancelled;
};

export type RunsCancelRunResponse = RunsCancelRunResponses[keyof RunsCancelRunResponses];

export type RunsDecideRunData = {
    body: DecisionCreate;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}/decision';
};

export type RunsDecideRunErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
};

export type RunsDecideRunResponses = {
    /**
     * Successful Response
     */
    200: DecisionView;
};

export type RunsDecideRunResponse = RunsDecideRunResponses[keyof RunsDecideRunResponses];

export type RunsRunEventsData = {
    body?: never;
    headers?: {
        /**
         * Last-Event-Id
         */
        'Last-Event-ID'?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * After
         *
         * Alternative to Last-Event-ID for clients without headers
         */
        after?: number | null;
    };
    url: '/v1/runs/{run_id}/events';
};

export type RunsRunEventsErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunsRunEventsError = RunsRunEventsErrors[keyof RunsRunEventsErrors];

export type RunsRunEventsResponses = {
    /**
     * RunEvent stream (see GET /v1/meta/run-events for the schema)
     */
    200: unknown;
};
