// Generated from services/api/src/backend/domain/adstudio/data/{iso3166,countries}.yaml.
// The API is the source of truth (422 unknown-geography); this list only drives the picker.

export type Hemisphere = "north" | "south" | "equatorial";

export interface Country {
  code: string;
  name: string;
  /** Present only for markets with season data on the API side. */
  hemisphere?: Hemisphere;
}

export const COUNTRIES: readonly Country[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina", hemisphere: "south" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia", hemisphere: "south" },
  { code: "AT", name: "Austria", hemisphere: "north" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain", hemisphere: "north" },
  { code: "BD", name: "Bangladesh", hemisphere: "north" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium", hemisphere: "north" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia", hemisphere: "south" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BR", name: "Brazil", hemisphere: "south" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "VG", name: "British Virgin Islands" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia", hemisphere: "north" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada", hemisphere: "north" },
  { code: "BQ", name: "Caribbean Netherlands" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile", hemisphere: "south" },
  { code: "CN", name: "China", hemisphere: "north" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia", hemisphere: "equatorial" },
  { code: "KM", name: "Comoros" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica", hemisphere: "north" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus", hemisphere: "north" },
  { code: "CZ", name: "Czechia", hemisphere: "north" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "CD", name: "DR Congo" },
  { code: "DK", name: "Denmark", hemisphere: "north" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic", hemisphere: "north" },
  { code: "EC", name: "Ecuador", hemisphere: "equatorial" },
  { code: "EG", name: "Egypt", hemisphere: "north" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia", hemisphere: "equatorial" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji", hemisphere: "south" },
  { code: "FI", name: "Finland", hemisphere: "north" },
  { code: "FR", name: "France", hemisphere: "north" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany", hemisphere: "north" },
  { code: "GH", name: "Ghana", hemisphere: "equatorial" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece", hemisphere: "north" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong", hemisphere: "north" },
  { code: "HU", name: "Hungary", hemisphere: "north" },
  { code: "IS", name: "Iceland", hemisphere: "north" },
  { code: "IN", name: "India", hemisphere: "north" },
  { code: "ID", name: "Indonesia", hemisphere: "equatorial" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland", hemisphere: "north" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel", hemisphere: "north" },
  { code: "IT", name: "Italy", hemisphere: "north" },
  { code: "JM", name: "Jamaica", hemisphere: "north" },
  { code: "JP", name: "Japan", hemisphere: "north" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan", hemisphere: "north" },
  { code: "KZ", name: "Kazakhstan", hemisphere: "north" },
  { code: "KE", name: "Kenya", hemisphere: "equatorial" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait", hemisphere: "north" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg", hemisphere: "north" },
  { code: "MO", name: "Macao", hemisphere: "north" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia", hemisphere: "equatorial" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta", hemisphere: "north" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico", hemisphere: "north" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia", hemisphere: "north" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco", hemisphere: "north" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal", hemisphere: "north" },
  { code: "NL", name: "Netherlands", hemisphere: "north" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand", hemisphere: "south" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria", hemisphere: "equatorial" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway", hemisphere: "north" },
  { code: "OM", name: "Oman", hemisphere: "north" },
  { code: "PK", name: "Pakistan", hemisphere: "north" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama", hemisphere: "equatorial" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay", hemisphere: "south" },
  { code: "PE", name: "Peru", hemisphere: "south" },
  { code: "PH", name: "Philippines", hemisphere: "north" },
  { code: "PN", name: "Pitcairn Islands" },
  { code: "PL", name: "Poland", hemisphere: "north" },
  { code: "PT", name: "Portugal", hemisphere: "north" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar", hemisphere: "north" },
  { code: "CG", name: "Republic of the Congo" },
  { code: "RO", name: "Romania", hemisphere: "north" },
  { code: "RU", name: "Russia", hemisphere: "north" },
  { code: "RW", name: "Rwanda", hemisphere: "equatorial" },
  { code: "RE", name: "Réunion" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "SH", name: "Saint Helena" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "MF", name: "Saint Martin" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "SA", name: "Saudi Arabia", hemisphere: "north" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore", hemisphere: "equatorial" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa", hemisphere: "south" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "KR", name: "South Korea", hemisphere: "north" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain", hemisphere: "north" },
  { code: "LK", name: "Sri Lanka", hemisphere: "equatorial" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SE", name: "Sweden", hemisphere: "north" },
  { code: "CH", name: "Switzerland", hemisphere: "north" },
  { code: "SY", name: "Syria" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "TW", name: "Taiwan", hemisphere: "north" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania", hemisphere: "equatorial" },
  { code: "TH", name: "Thailand", hemisphere: "north" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "TR", name: "Türkiye", hemisphere: "north" },
  { code: "VI", name: "U.S. Virgin Islands" },
  { code: "UG", name: "Uganda", hemisphere: "equatorial" },
  { code: "UA", name: "Ukraine", hemisphere: "north" },
  { code: "AE", name: "United Arab Emirates", hemisphere: "north" },
  { code: "GB", name: "United Kingdom", hemisphere: "north" },
  { code: "US", name: "United States", hemisphere: "north" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "UY", name: "Uruguay", hemisphere: "south" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela", hemisphere: "equatorial" },
  { code: "VN", name: "Vietnam", hemisphere: "north" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "AX", name: "Åland Islands" },
];

